apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "guestbook-app.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  ingressClassName: nginx
  rules:
    - host: guestbook.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "guestbook-app.fullname" . }}
                port:
                  number: 80