apiVersion: v1
kind: Service
metadata:
  name: {{ include "guestbook-app.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "guestbook-app.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 5000
      protocol: TCP
      name: http
  selector:
    {{- include "guestbook-app.selectorLabels" . | nindent 4 }}