services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - MYSQL_HOST=db
      - MYSQL_USER=guestbook_user
      - MYSQL_PASSWORD=943ruOu85D
      - MYSQL_DATABASE=guestbook_db
    depends_on:
      - db
    volumes:
      - .:/app
    restart: unless-stopped

  db:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=root_password
      - MYSQL_DATABASE=guestbook_db
      - MYSQL_USER=guestbook_user
      - MYSQL_PASSWORD=943ruOu85D
    volumes:
      - db_data:/var/lib/mysql
      - ./init_docker.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"
    restart: unless-stopped

volumes:
  db_data: