# values.yaml
replicaCount: 2

image:
  repository: chisporra77/guestbook-app
  tag: 1.5.0
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 5000

ingress:
  enabled: true
  className: "nginx"
  hosts:
    - host: guestbook.local
      paths:
        - path: /
          pathType: Prefix

mysql:
  auth:
    database: "guestbook_db"           # Name of the database to create
    username: "guestbook_user"         # User to create   
    
  # Additional initialization scripts (optional)
  initdbScripts:
    01-create-tables.sql: |
      CREATE TABLE IF NOT EXISTS guestbook_db.entries (
          id INT AUTO_INCREMENT PRIMARY KEY,
          name VARCHAR(100) NOT NULL,
          message TEXT NOT NULL,
          created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
      );
      
      INSERT IGNORE INTO entries (name, message) VALUES 
      ('System', 'Database initialized automatically');

resources:
  requests:
    memory: "128Mi"
    cpu: "100m"
  limits:
    memory: "256Mi"
    cpu: "200m"

# Healthcheck Probes
probes:
  enabled: true
  readiness:
    path: /
    port: 5000
    initialDelaySeconds: 20
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 3
  liveness:
    path: /
    port: 5000
    initialDelaySeconds: 30
    periodSeconds: 20
    timeoutSeconds: 5
    failureThreshold: 3

# Init Container configuration
initContainers:
  enabled: true
  mysql:
    image: mysql:8.0
    checkInterval: 5
    timeout: 60